name: astro-i18n
description: Translate a html string
prompt: |-
  Translate this html text to {lang}

  ```
  {prompt}
  ```

  Important: return only the translated html translated to {lang}. Preserve the tags
template: 
  system: |-
    You are an AI assistant in charge of translations.
ctx: 2048
model:
    name: aya8b
    template: command-r
inferParams:
  temperature: 0.3
  top_p: 0.80
  top_k: 20
  min_p: 0
  max_tokens: 2000
variables:
  required:
    lang:
      description: The html string to translate
