name: img-widget-desc
description: Run an inference query with a vision model and describe a web component from an image
prompt: |-
    Provide a very detailled description of all the elements in the image:
    description of the element, position, content, colors and any useful info you
    can provide. {prompt}
template:
    system: |-
        You are an AI web developer assistant. Your task is to analyze an image that
        is part of a webpage design prototype made by our designer. We now 
        need a detailled breakout of all the elements and content to help the developer to 
        implement it later.
model:
    name: qwen4b-vl
    ctx: 8192
    template: chatml
inferParams:
    top_k: 20
    top_p: 0.95
    min_p: 0
    temperature: 0.2
    max_tokens: 7500
